### ISSUE TITLE
Wrong structure with empty dicts depending on order

### ISSUE THREAD

**Issue by BenjaminGalliot** [JuliaData/YAML.jl#81]
Hello,

I noticed a strange behaviour with empty dicts:

```
import YAML
file_good = "test_good.yml"
data = Dict("key1" => [Dict("subkey1" => "subvalue1", "subkey2" => "subvalue2"), Dict()], "key2" => "value2")
YAML.write_file(file_good, data)
file_bad = "test_bad.yml"
data = Dict("dkey1" => [Dict("subkey1" => "subvalue1", "subkey2" => "subvalue2"), Dict()], "key2" => "value2")
YAML.write_file(file_bad, data)
```

file_good.yml:
```
key2: "value2"
key1:
  - subkey2: "subvalue2"
    subkey1: "subvalue1"
  - 
```

file_bad.yml:
```
dkey1:
  - subkey2: "subvalue2"
    subkey1: "subvalue1"
  - key2: "value2"
```

In the bad file, the structure becomes wrong, depending on the order the dict is read (that is why it was hard to reproduce this, I needed to try several names to make it appear).

Thank you for your investigation.

Sincerely.
